### ISSUE TITLE
"Get Started" Guide

### ISSUE THREAD

**Issue by RobertHosking** [memo330179/pi-drive-flask#3]
I'd like to set up a dev environment.

**Comment by memo330179** [comment]
Will write one soon

**Comment by RobertHosking** [comment]
Nice! The code currently in repo has a few syntax errors and class naming conflicts. Please push a minimal working version.

**Comment by memo330179** [comment]
Make sure you are using python 3.5 or higher. Might be useful to make a virtual environment

**Comment by RobertHosking** [comment]
Installed python 3.52
Still getting errors on `python run.py`
It does seem legitimate. Then again, I have no experience with flask.
```
# views.py
#
#
# we need to upload a file
# this is the simplest way I could do it
@media_api.route("/upload/<media_type>", methods=["POST"])
def upload_media(media_type):
    media_file = request.files['file']
    if media_type = "movie":
        #upload_movie(media_file)
        pass
    else if media_type = "tv":
        #upload_tv(media_file)
        pass
```

It seems to me that `if media_type = "movie":` should be `if media_type == "movie":`
and `else if` is not a python expression as far as I know.

Even after fixing those, I get naming conflicts with the `Resource` class brought in from `from flask_restful import Resource, Api` and this class definition `class Resource(flask_restful.Resource):` later on.

**Comment by memo330179** [comment]
Hmm make sure you have the most recent changes pulled. I'll make sure I have the most recent changes pushed.

**Comment by RobertHosking** [comment]
Pulled changes and it works!
